name: nordic_dfu_example
description: Demonstrates how to use the nordic_dfu plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_blue: 
    git:
      url: https://github.com/TOTHLIFECARE/flutter_blue
      ref: will-restore-state
  nordic_dfu:
    path: ../
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  uses-material-design: true

#  # To add assets to your application, add an assets section, like this:
#  assets:
#    - assets/file.zip
